<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0
 */

/**
 * Database `classinfo`
 */

/* `classinfo`.`bio` */
$bio = array(
  array('Name' => 'BIOL 1A. Introductory Biology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'GE Area: B2','Description' => 'Course one of two-semester sequence required of all biology majors. Thematic introduction to the unifying concepts of life science: chemical basis of life; cellular processes; energy metabolism; genetics; evolution.'),
  array('Name' => 'BIOL 1B. Introductory Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'First-time enrollees must take BIOL 1BL concurrently. Course two of a two-semester sequence required of all biology majors. Continuation of thematic introduction to the unifying concepts of life science: classification and diversity of life; survey of the living organisms; physiology; ecology and environmental biology. '),
  array('Name' => 'BIOL 1BL. Introductory Biology Laboratory','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Continuation of thematic introduction to the unifying concepts of life science: laboratory exercises in evolution, classification and diversity of life; survey of the living organisms; physiology; ecology and environmental biology'),
  array('Name' => 'BIOL 10. Life Science','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'GE Area: B2','Description' => 'How living things work and why they work that way. Biology from chemical and physical foundations to ecological and evolutionary processes. Biology and its relationship to human affairs. G.E. Breadth B2.'),
  array('Name' => 'BIOL 11. Plant Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'GE Area: B2','Description' => 'Structure, function, and development of plants. G.E. Breadth B2.'),
  array('Name' => 'BIOL 12. Animal Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'GE Area: B2','Description' => 'Structural and functional comparison of animals; principles and human implications of inheritance, evolution, and ecology; physiology as applied to man. G.E. Breadth B2.'),
  array('Name' => 'BIOL 20. Introductory Microbiology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Introduction to microbiology; principles and selected applications.'),
  array('Name' => 'BIOL 20N. Introductory Microbiology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Introduction to microbiology; principles and selected applications. Reserved for nursing major only.'),
  array('Name' => 'BIOL 33. Introductory Human Anatomy and Physiology','Units' => 'Units: 5','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Three units allowed for students with prior credit in human anatomy; 2 units allowed for students with prior credit in human physiology. An integrated study of the structure and function of the human body.'),
  array('Name' => 'BIOL 67A. Human Anatomy & Physiology I','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Not open to students with credit in BIOL 33, 64, or 65. Histology, cellular communication, embryological development, and the anatomy and physiology of the following human systems: integumentary, skeletal, muscular, nervous, and special senses.'),
  array('Name' => 'BIOL 67B. Human Anatomy and Physiology II','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'The anatomy and physiology of the following human systems: endocrine, cardiovascular, lymphatic/immune, respiratory, urinary, digestive, and reproductive as well as introductory nutrition and metabolism, exercise physiology, and human development and aging.'),
  array('Name' => 'BIOL 101. General Ecology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'The structure, function, organization, and regulation of populations, communities, and ecosystems. The role of evolution in environmental relationships.'),
  array('Name' => 'BIOL 101L. General Ecology Lab','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Laboratory focusing on ecological concepts, relevant published studies, simulation tools, and hands-on work with living material and investigating their responses to variation in their environments.'),
  array('Name' => 'BIOL 102. Genetics','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'CHEM 8 or CHEM 128A may be taken concurrently. Required of all biology majors. Fundamentals of inheritance, including an introduction to the underlying molecular mechanisms.'),
  array('Name' => 'BIOL 103. Cellular Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Fundamentals of inheritance and cellular biology for both prokaryotic and eukaryotic systems, including an introduction to the underlying molecular mechanisms.'),
  array('Name' => 'BIOL 104. Genetics and Cell Biology Lab','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Required of all biology majors. Must be taken a minimum of four semesters from completing BIOL 103. Basic techniques in molecular genetics and cell biology. No credit if BIOSC 140B taken prior to fall 2005.'),
  array('Name' => 'BIOL 105. Evolution','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Required of all biology majors. Evolutionary processes and patterns. Satisfies the senior major requirement for the B.S. in Biology.'),
  array('Name' => 'BIOL 110. Human Ecology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'The study of the relationships between humans and their environment, both natural and man-made; emphasis on scientific understanding of root causes of current environmental problems.'),
  array('Name' => 'BIOL 111H. Honors Experimental Design & Writing','Units' => 'Units: 1','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Admission to the biology honors program or permission of instructor. Experimental Design for Biologists offers an overview of the philosophy of science and the scientific method, and helps students establish the framework for their experimental projects.'),
  array('Name' => 'BIOL 112H. Honors Peer Instruction','Units' => 'Units: 1','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => 'Admission to the biology honors program or permission of instructor. The development of improved oral communication, reinforcement of foundational biology knowledge, and development of teaching skills through service as a peer-instructor in biology.'),
  array('Name' => 'BIOL 113H. Honors Colloquium','Units' => 'Units: 1','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Admission to the biology honors program, BIOL 1A and 1B, or permission of instructor. Students explore selected topics in biology through engagement with speakers. Speakers from within and outside the department and university will speak on topics in their specialty. The students will gain familiarity to current ideas and research in biology and gain experience evaluating and critiquing scientific research presentations and articles.'),
  array('Name' => 'BIOL 119. Molecular Virology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This is the study of viruses and viral diseases '),
  array('Name' => 'BIOL 120. Microbiology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Tiny tiny biology things'),
  array('Name' => 'BIOL 121. Medical Microbiology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => 'Learn about tiny lifesaving guys'),
  array('Name' => 'BIOL 122. Nonvascular Plants','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn about plants that don\'t live'),
  array('Name' => 'BIOL 123. Phycology','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn about the interworking of the mind and how to screw with people on a mental level'),
  array('Name' => 'BIOL 124. Vascular Plants','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Plants that DO live'),
  array('Name' => 'BIOL 125. Plant Taxonomy','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn how to taxedery a plant to perserve it'),
  array('Name' => 'BIOL 130. Invertebrate Zoology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => 'Learn about animals that are invertebrates'),
  array('Name' => 'BIOL 131. Parasitology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Learn all about discusting parasites and how to destroy them'),
  array('Name' => 'BIOL 132. General Entomology','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Learn what the heck entomology even is'),
  array('Name' => 'BIOL 133. Natural History of Vertebrates','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn about how vertebrates came to be'),
  array('Name' => 'BIOL 134. Ichthyology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn all about wovles and other wolf related families'),
  array('Name' => 'BIOL 135. Biology of Reptiles and Birds','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn how reptiles and birds work despite them being different species'),
  array('Name' => 'BIOL 136. Mammalogy','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn all about the biology of mammals'),
  array('Name' => 'BIOL 140. Plant Anatomy','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'There are so many plants in the world that one course can not contain them all'),
  array('Name' => 'BIOL 141. Histology','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Learn about the microanatomy of cells, tissues, and organs as seen through a microscope.'),
  array('Name' => 'BIOL 142. Vertebrate Embryology','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Investigate the processes by which animals develop.'),
  array('Name' => 'BIOL 143. Comparative Vertebrate Morphology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Comparative Vertebrate Morphology provides a comprehensive discussion of vertebrate morphology. The structure-function concept at the level of organs and organ systems is fundamental to an understanding of comparative evolutionary morphology.'),
  array('Name' => 'BIOL 144. Neuroanatomy','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 150. Molecular Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 151. Bioinformatics','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 152. Experimental Molecular Genetics','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 153. Microbial Genetics','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 155. Developmental Biology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 156. Plant Growth and Development','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 157. Immunology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 157L. Immunology Laboratory','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 158. The Biology of Cancer','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 160. Microbial Physiology','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 161. Plant Physiology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 162. Comparative Animal Physiology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 162L. Comparative Animal Physiology Lab','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 163. Advanced Human Physiology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 164. Hematology','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 165. Endocrinology','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 166. Neurophysiology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 169L. Physiology Laboratory','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 170. Microbial Ecology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 171. Terrestrial Ecology','Units' => 'Units: 4','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 172. Aquatic Ecology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 173. Marine Biology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 174. Animal Behavior','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 175. Case Studies in Ecology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 176. Field Methods Ecology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 177. Conservation Biology','Units' => 'Units: 4','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 178. Systematic Biology and Macroevolution','Units' => 'Units: 4','Usually_Offered_In' => 'Fall','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 179. Population Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => NULL),
  array('Name' => 'BIOL 180. Biology Colloquium','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'Repeatable up to 2 units','Description' => 'The aim of the Biology Colloquium is to expose students to selected topics in biology. Speakers from within and outside the department and university will speak on topics in their specialty. The course assumes basic knowledge of biology.'),
  array('Name' => 'BIOL 181. Seminar in Cellular and Molecular Biology','Units' => 'Units: 1','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'Trends and breakthroughs in cellular and molecular biology accessed through the primary literature.'),
  array('Name' => 'BIOL 189T. Topics in Biology','Units' => 'Units: 1-4','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 6 units','Description' => 'Prerequisite: permission of instructor. Investigation of selected areas in the field of biology. (Lecture and/or laboratory)

'),
  array('Name' => 'BIOL 189T. Biology Teaching and Outreach','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This will encourage students to teach biology to people K-12 and to reachout to people for better oppertunities'),
  array('Name' => 'BIOL 189T. Graphic Design for Scientists','Units' => 'Units: 2','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Investigates the impact of visual design on scientific figures and uses visual design to engage students in science, technology, engineering and mathematics disciplines'),
  array('Name' => 'BIOL 189T. High Altitude Biology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'High altitudes are characterized by differences in atmospheric pressure that vary predictably across elevational gradients. Hypoxia, in particular, is one of the most important factors that influences performance and survival in both plants and animals. In animals, biochemical changes in the blood-O2 transport protein hemoglobin (Hb), for example, have been shown to mitigate the effects of chronic exposure to hypoxia in high-altitude adapted populations. Biochemical adaptations in plant respiration and photosynthesis have allowed plants to survive in elevations above 5000 meters (16,000 feet). However, selection on Hb represents only one component of O2 transport. Important mechanistic changes also have occurred at other points of O2 transport involving both corrective and diffusive processes (e.g. breathing and pulmonary O2 diffusion, circulatory O2 delivery, and tissue O2 diffusion and metabolism). '),
  array('Name' => 'BIOL 189T. Pre-Health Perspective and Seminar','Units' => 'Units: 1','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This course will allow you to: Effectively utilize advising & career coaching resources as they navigate the UW,Prepare for profession of interest, including: Course & major planning Identifying opportunities for research, leadership & clinical exposure'),
  array('Name' => 'BIOL 189T. Introduction to Biological Computing','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'The goal of the class is to engage students in the field of ornithology. In lectures we will investigate the role of bird evolution and ecology on avian morphology, phylogeny, physiology, and behavior. Labs and field trips will provide hands-on experience with bird morphology, identification (visual and auditory), behavior, and data analyses'),
  array('Name' => 'BIOL 190. Independent Study','Units' => 'Units: 1-3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'Repeatable up to 6 units','Description' => 'See Academic Placement - Independent Study. Approved for RP grading.'),
  array('Name' => 'BIOL 199H. Honors Thesis in Biology','Units' => 'Units: 3','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => '','Description' => 'Preparation, completion, and submission of an acceptable thesis for the honors in biology designation.'),
  array('Name' => 'BIOL 204. Biology of Speciation','Units' => 'Units: 2','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Evolution of the species as a unit of biological organization.'),
  array('Name' => 'BIOL 208. Biological Field Studies','Units' => 'Units: 1-6','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Prerequisite: permission of instructor. Integrated studies or specialized topics, including botanical, environmental, microbiological, or zoological field studies. Approved for SP grading.

'),
  array('Name' => 'BIOL 224. Evolutionary Developmental Biology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This course examines principles and mechanisms of animal development. Emphasis will be held on the evolution of developmental pathways, and how the alteration of these pathways has led to the evolution of animal morphology.'),
  array('Name' => 'BIOL 225. Molecular Evolution','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Patterns and processes by which biological molecules evolve. Lecture topics include rates and modes of DNA sequence evolution, molecular phylogenetics, gene duplication, concerted evolution, genome organization, and application of computers to comparative'),
  array('Name' => 'BIOL 230. Foundations of Ecology','Units' => 'Units: 2','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Ideas and papers that defined ecology as an independent scientific discipline are discussed, both in the context of their time of publication and in comparison to current ecological paradigms. Time period covered is late 19th century to present.'),
  array('Name' => 'BIOL 240. Systems Ecology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Quantitative approach to the analysis of whole ecosystems including data acquisition and statistical treatment, conceptual and mathematical ecosystem modeling, and computer simulations in FORTRAN or BASIC. No programming experience needed.'),
  array('Name' => 'BIOL 241A. Molecular Biology I','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Fundamental topics in molecular biology are addressed, including protein and nucleic acid structure, DNA replication, transcription, translation, generic material exchange mechanisms, genome structure, recombination and transposition. A combination of lectures and research paper discussion are used in this course.'),
  array('Name' => 'BIOL 241B. Molecular Biology II','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Advanced topics in molecular biology are addressed, including gene regulation, recombinant DNA technology, protein trafficking, cell-cell communication, programmed cell death, oncogenes and cancer, RNA interference. A combination of lecturers and research paper discussion are used in this course.'),
  array('Name' => 'BIOL 242. Techniques in Protein Purification and Analysis','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Deals with the technologies relevant to protein isolation, purification, analysis, immobilization, and modification in micro and macro quantities.'),
  array('Name' => 'BIOL 243. Nucleic Acid Technology Lab','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'A lecture/laboratory course focusing on the technologies used in nucleic acid chemistry; specifically, synthesis, translation, mutagenesis, and genetic engineering.'),
  array('Name' => 'BIOL 244. Cell Culture Techniques','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'The theory and practice of in vitro propagation of eukaryotic cells, including growth characteristics, metabolic requirements, genetic analysis, and screening assays. Special focus is on cancer cell lines with the potential for stem cell manipulation relative to cell biology culture and application to biotechnology.'),
  array('Name' => 'BIOL 245. Industrial Biotechnology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Theory and current practices of bioprocessing, including hands-on experience with standard techniques and formulation of a strategic plan for a new technology or product.'),
  array('Name' => 'BIOL 248. Seminar in Molecular Biology and Biotechnology','Units' => 'Units: 1-2','Usually_Offered_In' => '','Additional_Information' => '','Description' => '(CHEM 248 same as BIOL 248.) Prerequisite: admission to the biology or chemistry graduate program. Preference will be given to students enrolled in the Master of Biotechnology Program. Reviews and reports on current literature in various aspects of biotechnology and molecular biology.

'),
  array('Name' => 'BIOL 250. Scientific Writing','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Prerequisite: permission of instructor. Prepare a writing sample to fulfill Graduate Writing Requirement; how to write a proposal for a research project, including language (composition for scientific writers), structure (elements of proposals), and content (literature review, scientific question). (3 lecture hours)

'),
  array('Name' => 'BIOL 251. Experimental Design for Biologists','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Experimental Design for Biologists offers an overview of the philosophy of science and the scientific method and helps students frame research questions and develop hypotheses, choose appropriate methods and design experiments, and interpret and present their experimental results. (Formerly BIOL 260T)

'),
  array('Name' => 'BIOL 255T. Topics in Botany','Units' => 'Units: 1-3','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 9 units','Description' => 'Prerequisite: permission of instructor. Investigation of new fields, areas not in current courses, or advanced studies in a given area. (Lecture and/or laboratory)

'),
  array('Name' => 'BIOL 256. Plant Development Genetics','Units' => 'Units: 3','Usually_Offered_In' => 'Fall','Additional_Information' => 'Repeatable up to 9 units','Description' => 'This seminar course is intended for graduate students and will cover recent progress made in plant molecular genetics to understand how plants develop and how they respond to the biotic and biotic environment.

'),
  array('Name' => 'BIOL 260T. Topics in Biology','Units' => 'Units: 1-3','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 9 units','Description' => 'Prerequisite: permission of instructor. Investigation of new fields, areas not in current courses, or advanced studies in a given area. (Lecture and/or laboratory)

'),
  array('Name' => 'BIOL 260T. Graphic Design for Scientists','Units' => 'Units: 2','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This will allow for scientists to better draw a parallel between mathematics, science, and art thought sketching up diagrams that represent the persons findings.'),
  array('Name' => 'BIOL 260T. Introduction to Biological Computing','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Biological computers use biologically derived molecules — such as DNA and proteins — to perform digital or real computations.'),
  array('Name' => 'BIOL 260T. Molecular Phylogenetics and Evolution','Units' => 'Units: 2','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 8 units','Description' => 'Application of molecular markers to studies of species, populations and natural history of aquatic and terrestrial organisms; Biodiversity and historical biogeography.

'),
  array('Name' => 'BIOL 265T. Topics in Physiology','Units' => 'Units: 1-3','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 9 units','Description' => 'Prerequisite: permission of instructor. Investigation of new fields, areas not in current courses, or advanced studies in a given area. (Lecture and/or laboratory)

'),
  array('Name' => 'BIOL 266. Neuroethology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Neuroethology links brain function to natural behavior. This course will explore the underlying neural and molecular mechanisms that drive animal behavior and how the nervous system has evolved and adapted to the specific challenges in the environment.

'),
  array('Name' => 'BIOL 267. Behavioral Endocrinology','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Interaction between hormones and behavior from an interdisciplinary perspective will be examined throughout this course. This interaction is bidirectional: hormones affect behavior and behavior can influence hormones. The course focuses on how prenatal hormonal levels influence hormone-behavior interactions as adults.'),
  array('Name' => 'BIOL 270T. Topics in Zoology','Units' => 'Units: 1-3','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 9 units','Description' => 'Prerequisite: permission of instructor. Investigation of new fields, areas not in current courses, or advanced studies in a given area. (Lecture and/or laboratory)

'),
  array('Name' => 'BIOL 272. College Science Teaching','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'This course is designed for graduate students in the sciences and graduate students in science education who are interested in improving their science teaching and their students learning, and in pursuing careers in college science teaching. Central Course Question: How do college students best learn science and how do we best teach them?'),
  array('Name' => 'BIOL 273. Applied Bioethics','Units' => 'Units: 1','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'This course explores historical and modern ethical issues in order to prepare students to understand and to address situations they will likely encounter in biological research. Topics include responsible data management, publications and authorship, negligence and fraud, conflict of interest, and the use of animals and humans in research. The course will combine brief background lectures with case study presentations and discussions.'),
  array('Name' => 'BIOL 274. Biostatistics & Experimental Design','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Application of statistical techniques to biological problems with emphasis on sampling, analysis of variance, experimental design, and regression techniques. Emphasis on analysis of real biological data and interpretation of results.'),
  array('Name' => 'BIOL 275. Biogeography','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Prerequisite: permission of instructor. Seminar in descriptive and ecological geography of animal and plant groups.

'),
  array('Name' => 'BIOL 276. Biology of Climate Change','Units' => 'Units: 3','Usually_Offered_In' => 'Spring','Additional_Information' => '','Description' => 'The course examines the physical mechanisms and drivers of the earth\'s climate system, specifically analyzing biosphere-climate interactions. Using a lecture-discussion format, the course evaluates climatic impacts on the biosphere integrating across spatial (cell-to-ecosystem) and temporal (hours-to-decades) scales.'),
  array('Name' => 'BIOL 280. Biology Colloquium','Units' => 'Units: 1','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'Repeatable up to 2 units','Description' => 'The aim of the Biology Colloquium is to expose graduate students to selected topics in biology. Speakers within the department and outside the department and university will address topics in their specialty.'),
  array('Name' => 'BIOL 281. Seminar in Biological Science','Units' => 'Units: 1-2','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 3 units','Description' => 'Prerequisite: permission of instructor. Reviews and reports on current literature in the various phases of biology.

'),
  array('Name' => 'BIOL 290. Independent Study','Units' => 'Units: 1-3','Usually_Offered_In' => '','Additional_Information' => 'Repeatable up to 6 units','Description' => 'See Academic Placement regarding Independent Study. Approved for SP grading.

'),
  array('Name' => 'BIOL 295. Research','Units' => 'Units: 2-6','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Prerequisite: permission of instructor. Independent research by the advanced graduate student.'),
  array('Name' => 'BIOTC 298. Biotechnology Culminating Project','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Shows what you\'ve learned in Biotechnology'),
  array('Name' => 'BIOTC 298C. Project Continuation','Units' => 'Units: 0','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Project Continuation

'),
  array('Name' => 'BIOTC 299. Thesis','Units' => 'Units: 4','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'Preparation, completion, and submission of an acceptable thesis for the master\'s degree.'),
  array('Name' => 'BIOTC 299C. Thesis Continuation','Units' => 'Units: 0','Usually_Offered_In' => '','Additional_Information' => '','Description' => 'For continuous enrollment while completing the thesis. May enroll twice with department approval. Additional enrollments must be approved by the Dean of Graduate Studies.'),
  array('Name' => 'CI 161. Methods and Materials for Teaching Science','Units' => 'Units: 3','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'EHD 154B. Final Student Teaching Seminar - Biology','Units' => 'Units: 1','Usually_Offered_In' => '','Additional_Information' => '','Description' => NULL),
  array('Name' => 'EHD 155B. Student Teaching - Biology','Units' => 'Units: 5-10','Usually_Offered_In' => 'Fall / Spring','Additional_Information' => 'Repeatable up to 20 units','Description' => NULL)
);
